version: '3.8'

services:
  app:
    build: .
    container_name: timeweb_metrics
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config.yaml:/app/config.yaml:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
